const $=s=>document.querySelector(s);const loginPanel=$('#loginPanel'),dashboard=$('#dashboard'),logout=$('#logout'),apps=$('#apps'),template=$('#appTemplate');
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},cache:'no-store',...options});if(r.status===401)throw new Error('AUTH');if(!r.ok){let m='Request failed';try{m=(await r.json()).error||m}catch{}throw new Error(m)}return r.headers.get('content-type')?.includes('json')?r.json():r.text()}
function showLogin(){loginPanel.classList.remove('hidden');dashboard.classList.add('hidden');logout.classList.add('hidden')}
function showDashboard(){loginPanel.classList.add('hidden');dashboard.classList.remove('hidden');logout.classList.remove('hidden')}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.valueOf())?String(v):d.toLocaleString()}
function stateInfo(deploy){const s=deploy?.state||'idle';if(s==='running')return['Deploying','busy'];if(s==='failed')return['Failed','fail'];return['Healthy','ok']}
async function runDeploy(id,action,button){if(!confirm(`${action==='full'?'Deploy latest version of':'Restart'} ${id}?`))return;button.disabled=true;try{await api(`/api/admin/apps/${id}/deploy`,{method:'POST',body:JSON.stringify({action})});$('#updated').textContent=id==='portal'&&action==='full'?'Games Portal deployment started. After it finishes, click Refresh to load the new admin UI.':`${action==='full'?'Deployment':'Restart'} started. Click Refresh to update status.`}catch(e){alert(e.message==='AUTH'?'Session expired.':e.message);if(e.message==='AUTH')showLogin()}finally{button.disabled=false}}
async function loadLog(id,pre){try{pre.textContent=await api(`/api/admin/apps/${id}/deploy-log`)}catch(e){pre.textContent=e.message}}
async function load(){try{const data=await api('/api/admin/status');showDashboard();apps.innerHTML='';for(const item of data.apps){const node=template.content.cloneNode(true),article=node.querySelector('.app'),[label,cls]=stateInfo(item.deploy);article.dataset.id=item.id;node.querySelector('.name').textContent=item.name;const link=node.querySelector('.url');link.textContent=item.url;link.href=item.url;const dot=node.querySelector('.dot');dot.classList.add(cls);node.querySelector('.state').textContent=label;node.querySelector('.commit').textContent=item.deployed?.revision?item.deployed.revision.slice(0,12):'Not recorded';node.querySelector('.deployedAt').textContent=fmtDate(item.deployed?.deployedAt);const deploy=node.querySelector('.deploy'),restart=node.querySelector('.restart');deploy.onclick=()=>runDeploy(item.id,'full',deploy);restart.onclick=()=>runDeploy(item.id,'restart',restart);const toggle=node.querySelector('.log-toggle'),arrow=node.querySelector('.log-arrow'),panel=node.querySelector('.log-panel'),pre=node.querySelector('.log');panel.addEventListener('click',event=>event.stopPropagation(),true);panel.addEventListener('mousedown',event=>event.stopPropagation(),true);toggle.onclick=async event=>{event.preventDefault();event.stopPropagation();const opening=panel.classList.contains('hidden');if(opening){panel.classList.remove('hidden');toggle.setAttribute('aria-expanded','true');arrow.textContent='▾';await loadLog(item.id,pre)}else{panel.classList.add('hidden');toggle.setAttribute('aria-expanded','false');arrow.textContent='▸'}};apps.appendChild(node)}$('#updated').textContent=`Updated ${new Date().toLocaleTimeString()}`}catch(e){if(e.message==='AUTH')showLogin();else $('#updated').textContent=e.message}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});$('#password').value='';await load()}catch(err){$('#loginError').textContent=err.message==='AUTH'?'Invalid credentials':err.message}});$('#refresh').onclick=()=>window.location.reload();logout.onclick=async()=>{try{await api('/api/admin/logout',{method:'POST'})}catch{}showLogin()};load();
