'use strict';
const fs=require('node:fs');
const os=require('node:os');
const https=require('node:https');
const {spawnSync}=require('node:child_process');

function command(command,args=[]){try{const r=spawnSync(command,args,{encoding:'utf8',timeout:2500});return String(r.stdout||r.stderr||'').replace(/\x1b\[[0-9;]*m/g,'').trim();}catch{return''}}
function memory(){try{const text=fs.readFileSync('/proc/meminfo','utf8'),values={};for(const line of text.split('\n')){const m=line.match(/^([^:]+):\s+(\d+)\s+kB$/);if(m)values[m[1]]=Number(m[2])*1024}const total=values.MemTotal||os.totalmem(),available=values.MemAvailable||os.freemem(),used=Math.max(0,total-available);return{total,used,available,percent:total?used/total*100:0}}catch{const total=os.totalmem(),available=os.freemem(),used=total-available;return{total,used,available,percent:total?used/total*100:0}}}
function disk(root){try{const s=fs.statfsSync(root),total=Number(s.blocks)*Number(s.bsize),free=Number(s.bavail)*Number(s.bsize),used=Math.max(0,total-free);return{total,used,free,percent:total?used/total*100:0}}catch{return{total:0,used:0,free:0,percent:0}}}
function osName(){try{const text=fs.readFileSync('/etc/os-release','utf8'),m=text.match(/^PRETTY_NAME=(?:"([^"]+)"|(.+))$/m);return(m?.[1]||m?.[2]||`${os.type()} ${os.release()}`).trim()}catch{return`${os.type()} ${os.release()}`}}
function pm2(){const version=command('pm2',['-v'])||'Unavailable',raw=command('pm2',['jlist']);let rows=[];try{rows=JSON.parse(raw)}catch{}const states=new Map(rows.map(row=>[String(row.name),String(row.pm2_env?.status||'unknown')]));return{version,states}}
function nginx(){const raw=command('nginx',['-v']);const version=(raw.match(/nginx\/([^\s]+)/)||[])[1]||'Unavailable',active=command('systemctl',['is-active','nginx'])==='active';return{version,active}}
function check(url){return new Promise(resolve=>{let settled=false;const done=value=>{if(settled)return;settled=true;resolve(value)};const req=https.get(url,{timeout:2500,headers:{'User-Agent':'games-portal-admin-health'}},res=>{res.resume();done({online:Boolean(res.statusCode&&res.statusCode<500),status:res.statusCode||0})});req.on('timeout',()=>{req.destroy();done({online:false,status:0})});req.on('error',()=>done({online:false,status:0}))})}
async function getVmSnapshot(root,targets){const pm=pm2(),ng=nginx(),endpointDefs=[['Portal',targets.portal.url],['Admin','https://admin.129.146.112.160.sslip.io'],['Backgammon',targets.backgammon.url],['Preferans',targets.preferans.url]],checked=await Promise.all(endpointDefs.map(async([name,url])=>({name,url,...await check(url)})));const services=[{name:'nginx',online:ng.active,detail:ng.active?'running':'stopped'},...Object.values(targets).map(t=>{const state=pm.states.get(t.process)||'offline';return{name:t.process,online:state==='online',detail:state}})];return{health:services.every(s=>s.online)&&checked.every(e=>e.online)?'healthy':'warning',load:{one:os.loadavg()[0],cpus:os.cpus().length},memory:memory(),disk:disk(root),uptimeSeconds:os.uptime(),services,endpoints:checked,platform:{os:osName(),arch:`${os.platform()} ${os.arch()}`,node:process.version,pm2:pm.version,nginx:ng.version}}}
module.exports={getVmSnapshot};
